apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: mysql-operator-system
  labels:
    app.kubernetes.io/name: mysql-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: mysql-operator
      containers:
        - name: operator
          image: roflmaoinmysoul/mysql-operator:1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi