{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homework.clusterRoleName" . }}
  labels:
    {{- include "homework.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - "/metrics"
      - "/metrics/*"
    verbs: ["get"]
{{- end }}