apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-homework
  namespace: homework
spec:
  storageClassName: sc-homework
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
